env:
  es2021: true
  node: true

parserOptions:
  sourceType: module

plugins:
  - import

extends:
  - eslint:recommended
  - airbnb-base
  - plugin:import/recommended

rules:
  no-console: 0
  import/extensions: 0
